### PR TITLE
Fix Play Store icon for iOS

### PR DESCRIPTION
**Pull request by GroovinChip**

### CODE REVIEW

**Comment by lukepighetti** [comment]
Hey @GroovinChip ! I believe any link or mention of the Play Store is not allowed on iOS. If you could please remove all links and mentions that would be appreciated. I would like to try to get this on the AppStore if possible.

**Comment by GroovinChip** [comment]
Sure thing!

**Comment by GroovinChip** [comment]
Added new commit to remove play store mentions

**Comment by lukepighetti** [comment]
LGTM!

**Pull request merged**
